### ISSUE TITLE
Create Accomodations page

### ISSUE THREAD

**Issue by digitaldelirium** [digitaldelirium/MacsBackend#4]
- [ ] Implement RVInfo component for Lilypad and Lakeview trailers
- [ ] Create shared amenity list between trailers
- [ ] https://app.gitkraken.com/glo/board/XEPkppJoLwAPIcBU/card/XEPlmJJoLwAPIcBx
